language: java
jdk:
  - openjdk6
  - openjdk7
branches:
  only: 
    - master
before_install:
  - mkdir -p ~/_build/
script: 
  - javac HelloWorld.java -d ~/_build/

notifications:
  emails:
    - takeno@val.co.jp
  on_success: always # default: change
  on_failure: always
