language: java
jdk:
#  - openjdk6
  - openjdk7
branches:
  only: 
    - master
#env:
#  global:
#    - AWS_DEFAULT_REGION=ap-northeast-1
#    - secure: "nhCB4Ywyaw7m4qJx5tIfMKZ5pwlFb50g8CqaB3aIz5yxKg2QETrvW/p9Ph9QIjJV8EdkZmu3nJWa5fTodU25MjlHlXkczSDRMcXDCpzS0UEUwc1Vv46c/wppxhqV3ItjaBy0tTgbH8R/Mv9LWXrVBMSMlfObFv4+0q1X31A1dh8rIYgKXJ7meFRZEJ/kIo3OmOFVqilBG9U5ydkxcV90mc0eUcJE8UP09JNNtz0aQgq1Dw6FuNE4ku1VDnxGXaZ2IFrUjScOZd/2nscutEdxxC7K5u8djEbOTtx6rr+0nCAjWNUsm8kQ4yXEHOX8KtiU4feuD86W85N0xydRcED6Bs4B7Z7/fHLeYmWd7WNAABKFluc3wQINsbjufGGJAKFqQGlJbizwKYqgSKBPYAOO1scw0NFU4w57IDTI88jHb3v/sauN4OlnwcxItDxGkmAW7qqfnH9betUAzAJR2yfU3MuucYy1A/lrE99DHf+Jh7ziutNUJz6hr3qcYNWb7Rzl5K7IFmMB866F0bKVlXtyqC8bBOD8wAeZtqoynITa5TkrOLFAcvSS/sHhoYcJSy1w9O46dc3NnJ3ObmogmqckxW0VUSQs/lmSXfqI1feDHMIPRy8mcWYteZKxmioEnp8vzm7DLfaydhPvhSrHeCDFR1twzEcXbQuZwyfmJjNc7Oc=" #AWS_ACCESS_KEY_ID
#    - secure: "N50tAgAPUgX85lFkW6PrUJwsOf7VevPkmNdpTpXklURAjTr679SXrFBTxOHhqw4sRimoD6gsTP61P6wQiZlXQRpVe+DvH4yEHzb+/GUH/SGoxHLfE6H+d5T3iAoLe1ySViW6i2o8nLZs7zP/lhOQY2cn1DpJL9irFwB/7WyQrNhEkXts5kcb/ZsYnhbbbEURXrq3uoFSxTPA25AKL9BN+beNTfqnJe1w99BZoTYqan2bmKqOl3zhXn6vJdKWVs+yfFj2zrloC3sMr+F2wdqyOc/MXAkvvXY/FdT3uNyyepLNK87LSxV7o2ok0BWNs3H+j/OuE70I9bOv991WXT7M2g9rcpx3g9Xi45C8fxWthc1MsaBw+Udz3WVhRMDNmRo5yDHCPvHV63ooZHquY/Hgsdn0BMv5uQ4GuD42bh9BlVePKKyh8ztZKwFOzSDqvdbYnIvV4bzB6GO9hIEMwk9j8uL5WvJ9QLE59XLbrBOtO08ojJ1h8QUcWVksUJhd6CUi6biTGFrZEf/uUQ2tQ6GUWhqu4oh7nlZ3Oefa9BaXoZ0KOPvzxjEe44/EKGpHbP6GTLuDMJfFWe+pmAMxIln6pqqsItWwS0nLzbj51m5OWCsnreSDqi2l+iUdmlIoBZf8ZkADjxZJySZq7yz2MoMfuF/C13YB1Dv5q0LJb1DcDxQ=" #AWS_SECRET_ACCESS_KEY
before_install:
  - eval `ssh-agent -s`
  - chmod 600 ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in infrakey.pem.enc -out ./infrakey.pem -d
  - mv infrakey.pem ~/.ssh/
  - chmod 600 ~/.ssh/infrakey.pem
#install:
#  - sudo pip install awscli
before_script:
  - mkdir -p _build
script: 
  - javac HelloWorld.java -d _build

#deploy:
#  # S3固定
#  provider: s3
#  # 暗号化したアクセスキー
#  access_key_id: 
#    secure: "ey9NGFVsXYGHW9EBh/yclNlkSnRjxJFcS5vP6AfvJutdaNPJEug2sbLGgfOArbzqEKAOCRqB9v18QXSdQEgd0lyN6w2GTkhDkFttQhvYD0uIU/Unnnap6RT+j2GdLkwru3TMR06vwwwW0dLbCrWLhtggN+jVjNJrXbDOEZ8bo0UJjfeX7oQPKcP9GuHqfFZN/1PDxAKs8r3JcCTXQouKHmH3rTIBsxO5/7xXQNe2Og5qY9cYbdrR6Uez3AGRoIj21HAyWGu8AvoNQiOgY/u0vjVHwuVS2RK8V3AcLqeKrf8S4LSxOY99yZiW6UEdvJUvtIzhX9KWr1Xp/sC+tl8G1mVQjTLefj12+X56lsMzmu8T5nOH3gQ5ZSV8ur7u7l3eY5eYM5HNtjCoywwnTGNmyPsoi+zNxOACmu3hICZT//fkloYqQ5tpvfD56iCDavxkN87gNeEbvvx8/8htERYvUveRlw6mByJNFaDK/wWz+YhCRGWO+5y1b6Z19sz1RObcxhgMYtEVLD1cDWGQCOj/Bl5T/R2WTrlHZJcN+hoC63F1vqr/jWtx9akdGPPX2iykaHOWF2qB2YjLuXakF6LoNb+bOlRi3CcpQJ0fb7kYg14qm04N1+2HN/S8RYpZFmAKE4i4ZAGZwsTSF3DNtMtJhtfzrhDm9nVsMrLkiTnVr/Q="
#  # 暗号化したシークレットキー
#  secret_access_key:
#    secure: "F44DviHsgifQi6WbvVMj7vf8ZCleWfbm3u9s/i7CgHbS9RIyvuh8ulqlTYTeR6/oiP5IJFCHZdyO2G6nAP66CUETUVHwmt4gbyye+uRSW3mMHwyINj29FxOajJhicBXHQPzBggCUcXmu92AA4Jpl64K8zWASWcd5WvBEEjNcyqDQpPZupulyxNahO9VniJTI5PSLXxoZROIw3d4OfZ+DUuEaKREDHlWH6fJ3Wm7Ljn/jLbNBPlf9b5wG/JRfioUTEkzFbwnQWxIdLJAgssvcrVvwnINWVezvzWOY77YY1uNo42Xog1WVJohrNtUU6F/gHgFl1kHEyn63QcRqbKKsUCwhmZ3aV5OUJ8fquuAFWAw3SamxtYGBwpcCF6ekZl1dpCtOk39H2EXI68K9dDvKp68VqReUTsyM4IyYCv2U9ey69fYlkvA4w+LGRW0NaIFEyIzG6QH96AbxXIhxLCPn1h5futWwJ2nd9IdVuVeVpAawPZQi74b405jHTUCLC3ICIJLxgMj9EaKaJpogjYt5ziJkm8dWd1whAjYEW7wuVIDUtHsHHHXbzcb9IcASxe9jDG8MCtufDtEg23xJuojDHB0Wwkk+FVzdZQtZyv3+F2BHDV/vsfZ5SX26lcnegV+Gq4UPwBpSlaCfQNmUlv6IYuZcy/HRhijZn6nc8YRXB3k="
#  # 対象のバケット名
#  bucket: bserv-cibuilds
#  # リージョン
#  region: ap-northeast-1
#  # エンドポイント
#  endpoint: s3-ap-northeast-1.amazonaws.com
#  # ビルド後のクリーンアップを抑制する
#  skip_cleanup: true
#  # Travis側のビルド結果のディレクトリ、この内容をs3にputする
#  local-dir: _build
#  # s3側のディレクトリ、このディレクトリにputする
#  upload-dir: travisci

notifications:
  on_success: always
  on_failure: always
  email:
    - takeno@val.co.jp

## 成功時と失敗時にそれぞれスクリプトを実行させる
#after_success: 
#  - chmod +x .travis/after_success.sh
#  - .travis/after_success.sh "テストです。"
#after_failure: 
#  - chmod +x .travis/after_failure.sh
#  - .travis/after_failure.sh "テストです。"

#after_success: 
#  - aws ec2 start-instances --instance-ids i-f5a9e46a
  - ssh -i ~/.ssh/infrakey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@52.197.222.172 sudo "cd /root/work//my_project_aws/; vagrant up --provider=aws;"
